### ISSUE TITLE
onConnect doesn't work (well, works in a strange way)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac#654] opened 2021-09-21 19:10 UTC
See https://makecode.microbit.org/_RVeCwjgyUAmA

The onConnected handler doesn't run on start. Note that it does run when you press the A button.
Then the second time you press the A button, the button hander runs. So, from a fresh state
- the LED pixels stay off when you run the program. 
- first press of button A turns the LEDs green
- second press of button A turns the LEDs red

```
modules.ledPixel1.onConnected(() => {
    modules.ledPixel1.setBrightness(85)
    modules.ledPixel1.setAll(0x00FF00)
})

input.onButtonPressed(Button.A, function() {
    modules.ledPixel1.setBrightness(85)
    modules.ledPixel1.setAll(0xFF0000)
})
```

**Comment by pelikhan** [comment] 2021-09-21 20:09
Duplicate of https://github.com/microsoft/jacdac/issues/653

**Closed by pelikhan** 2021-09-21 20:09 UTC
Labels: bug, makecodeintegration, hackathon, P0
