### ISSUE TITLE
support for client expressions

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac#453] opened 2021-06-09 15:02 UTC
Client commands provide a js expression to be evaluated on the client. See LED.fade which calls into LED.animate.

```
role.animate((color >> 16) & 0xff, (color >> 8) & 0xff, (color >> 0) & 0xff, speed * 0xff)
```

**Comment by tballmsft** [comment] 2021-06-09 15:07
duplicate of https://github.com/microsoft/jacdac/issues/445?

**Closed** 2021-06-09 15:13 UTC
Labels: feature, vm
