### ISSUE TITLE
LED ring does not light up without a pause between setting the brightness and turning the LEDs on

### ISSUE THREAD

**Issue by minki710** [microsoft/jacdac#1198] opened 2022-08-07 15:36 UTC
The LED ring does not light up without the "set led brightness" in Makecode. I did not see documentation related to this. Also, using Makecode, the LED ring will not light up if the code block "set led" to a color is immediately following the "set led brightness" code block. A pause of 200ms was required between the "set led brightness" and "set led" to a color. Or, other code blocks are used before setting the LEDs to a light up.

**Comment by dsssssssss9** [comment] 2022-08-07 16:17
Good Find minki710

On my setup the pause has to be AT LEAST 222ms...

i have found a sort of workaround if you are interested is to set both brightness = 0 & colour = Black plus the pause into the ONSTART block

Once this is done all future SET LED / SET BRIGHTNESS seem to work without needing any such pause each time.

It seems almost as if the code in the ONSTART block " wakes up" whatever the problem is?
![microbit-screenshot](https://user-images.githubusercontent.com/30810847/183300572-106d7f02-a981-4ac6-8ec4-ce7aab899836.png)

**Comment by pelikhan** [comment] 2022-08-08 20:25
This is a great find. I was able to repro the issue

**Comment by pelikhan** [comment] 2022-08-09 18:57
@mmoskal  To repro: build pxt-jacdac/led and press A

**Comment by pelikhan** [comment] 2022-08-09 22:27
@minki710 we fixed `set all to` to not require the `set brightness` anymore (in 1.8.19). The interaction with `set all` and `set brightness` is still to be fixed.

**Comment by minki710** [comment] 2022-08-10 11:39
that's great! what is the default brightness?

**Comment by mmoskal** [comment] 2022-08-10 12:36
The default brightness depends on the LED hardware. In case of KB LED ring it's 39%.

**Comment by pelikhan** [comment] 2022-08-10 16:00
This issue is fixed in v1.8.20 . You'll get that version when starting a new project or go to the Explorer file view in JavaScript and click the update button. Thank you for reporting!

**Closed by pelikhan** 2022-08-10 16:00 UTC
Labels: bug, makecodeintegration, makecode clients
