### ISSUE TITLE
Kittenbot Jacdac-Power module (Kit B) is displayed twice as UE21 and KA82

### ISSUE THREAD

**Issue by fabianhugo** [microsoft/jacdac#1345] opened 2024-01-08 11:36 UTC
**Describe the bug**
A brief search did not show a duplicate issue.
Kittenbot Jacdac-Power module (Kit B) is displayed twice as UE21 and KA82 in the Jacdac Dashboard:
![grafik](https://github.com/microsoft/jacdac/assets/32654742/fb6af0ec-24ce-42e8-95ec-f90c857c7e15)

In makecode.microbit.org the power module is not displayed below the simulator. 

**To Reproduce**
1. Flash Jacdac firmware to microbit 
2. Go to jacdac [dashboard](https://microsoft.github.io/jacdac-docs/dashboard/)
3. Connect power module
4. Power module appears twice as UE21 and KA82

**Expected behavior**
Only one instance of the power module should be shown.

**Comment by fabianhugo** [comment] 2024-01-09 10:42
Sure. In this trace I connected the power module after a couple of seconds and unplugged it a couple of seconds later.
[trace_power.jd.txt](https://github.com/microsoft/jacdac/files/13872566/trace_power.jd.txt)

**Comment by pelikhan** [comment] 2024-01-09 18:31
@xmeow @smfox10 please take a look

**Comment by xmeow** [comment] 2024-01-10 02:06
@fabianhugo Thank you for the feedback. Actually there is two separate power supply controllers on the module as discussed here: https://github.com/microsoft/jacdac/discussions/373 
But only one should be working at same time if there is external wiring to connect the two power supply together.

**Comment by smfox10** [comment] 2024-01-10 02:09
@fabianhugo 
On the Jacdac platform, there are two Jacdac power modules displayed (you can see two PADAUK ICs), which is not a bug. They are responsible for controlling the power on/off of the two Jacdac interface channels.

On the Makecode platform, the power module is not displayed. This decision was made in communication with Peli. Since Makecode platform programming is simple and there is no need to turn off the module, the power is generally kept on. Therefore, the icon was hidden.

**Comment by pelikhan** [comment] 2024-01-10 02:37
I will add a note on the device page. It seemed like a good idea to hide them... but we could revisit this decision.

**Comment by pelikhan** [comment] 2024-01-11 16:15
Fixed by https://github.com/microsoft/jacdac-docs/pull/280

**Closed by pelikhan** 2024-01-11 16:15 UTC
