### ISSUE TITLE
Handle MakeCode Arcade + micro:bit in pxt-jacdac

### ISSUE THREAD

**Issue by jamesadevine** [microsoft/jacdac#344] opened 2021-04-13 10:22 UTC
https://github.com/microsoft/pxt-jacdac/blob/master/hw.cpp#L194

The extension does not currently work as is in Arcade. This is because #ifdef MICROBIT_CODAL is never true because MICROBIT_CODAL is not defined in arcade.

**Comment by mmoskal** [comment] 2021-04-15 18:38
Well that is by design, since there is no uBit object in Arcade. We need to add:

```typescript
namespace config {
    export const PIN_JACK_TX = DAL.P0_12
}
```

to n3/config.ts in Arcade. For the time being, you can add it to your program.

**Comment by jamesadevine** [comment] 2021-04-16 13:43
Yup, I know. Was just making an issue for it

**Comment by pelikhan** [comment] 2021-04-20 17:40
@mmoskal can i assign this to you?

**Comment by mmoskal** [comment] 2021-04-20 19:19
@jamesadevine can you test this build https://arcade.makecode.com/app/e8fb53191ad1fa21997a58a8dcc1469218fe2f0c-c92e15dd3e ? I don't have arcade shield with JD handy

**Closed** 2021-04-21 13:06 UTC
Labels: arcadeshield, bug, javascript

**Comment by pelikhan** [comment] 2021-04-21 13:08
I pushed this fix to beta as well.

**Comment by jamesadevine** [comment] 2021-04-22 13:16
>@jamesadevine can you test this build https://arcade.makecode.com/app/e8fb53191ad1fa21997a58a8dcc1469218fe2f0c-c92e15dd3e ? I don't have arcade shield with JD handy

Yes! Works perfectly!

[arcade-jacdac.zip](https://github.com/microsoft/jacdac/files/6358493/arcade-jacdac.zip)
