### ISSUE TITLE
not possible to enter a product ID in the device catalog registration page?

### ISSUE THREAD

**Issue by sehodges** [microsoft/jacdac#1140] opened 2022-06-20 22:22 UTC
I tried to manually enter (well, copy-paste) the product ID into the device [catalog registration page](https://microsoft.github.io/jacdac-docs/tools/device-registration/) but I did not see how to. I can click to generate a random ID or import an ID from a device on the bus, but not paste in the random ID that was already generated at firmware build time.

![image](https://user-images.githubusercontent.com/12393831/174683786-e426b93e-7ce9-4415-8da1-e13f26474150.png)

**Comment by pelikhan** [comment] 2022-06-28 14:00
Tempted to close this as by design. If you cannot import your product identifier, it's probably not ready to be registered.

**Closed** 2023-01-25 17:01 UTC
Labels: enhancement, p3, web
